### ISSUE TITLE
Using GUID for object id

### ISSUE THREAD

**Issue by dev-zetta** [lance-gg/lance#104]
Hello there,

the object IDs are a simple indexed numbers. Is it possible to use GUID instead? Or are those numbers also indices to arrays?

**Comment by namel** [comment]
Using UUID's would increase the size of the networking payload, and we are trying to keep these packets as small as possible.

**Comment by dev-zetta** [comment]
@namel Changing the type of the ID to String would be all that's needed. It would still be possible to use both integers and GUIDs.

**Comment by OpherV** [comment]
@dev-zetta It's not a matter of type, rather a matter of size.  

How many IDs are in a game at any given state? Let's think of a bad-case scenario.
You can represent numbers up to 65536 with 16 bits, or 2 bytes, so if you had to send 1000 of these IDs it would 2Kb. Updates are sent multiple times per second, so that that adds quite quickly.

A UUID is a 128 bit number, which is 8(!) times larger. So sending 1000 IDs would take 128000 bits, or 16000 bytes, or 16kb. That's just for the IDs, without any overhead or data associated with them.

Plus with UUIDs you can't make any optimizations like sending IDs as incremental numbers.
See https://gafferongames.com/post/snapshot_compression/
