### ISSUE TITLE
What is the purpose of the Serializer?

### ISSUE THREAD

**Issue by ManzanaNaranja** [lance-gg/lance#143]
On the lance documentation for the Serializer, it says "The Serializer is responsible for serializing the game world and its objects on the server, before they are sent to each client. On the client side the Serializer deserializes these objects."

Why do we need to serialize objects when broadcasting the game world data? I'm confused on what the serializer is doing and its purpose. Can someone please explain this to me?

Thanks in advance.

**Comment by OpherV** [comment]
Hi @ManzanaNaranja 
Essentially, you want to transfer as little data as possible over the wire since updates are frequent and bandwidth is limited. The serializer facilitates this by encoding the game state (world data) into a compact binary form, the output of which is sent over the wire and received by the deserializer to be unpacked back into the world state data structure in the client.

There's more information here:
https://lance-gg.github.io/docs_out/tutorial-guide_serialization.html
