### ISSUE TITLE
Serializer add String type

### ISSUE THREAD

**Issue by z3t0** [lance-gg/lance#46]

**Comment by OpherV** [comment]
@z3t0 The netscheme is aimed for frequently changing data for networked entities. Common examples are position, ammo, health etc'. The serializer is then used to convert the data to binary to minimize the data that goes over the wire.

Regarding strings - 

- If it's something that doesn't change, you can just include that in the class definition. 
- If it's a descriptor, you can include the string in the class and an int on the netscheme. For example, you have an active enchantment on a character entity and it could be one of five different enchantments: have an enchantmentId in the netscheme and a map from an id to a string on the class
- If you're trying to send a one time string data, like a player name, you can just use the `emit` function with the string parameter and catch it on the other side. e.g. `emit('nameChange', 'playerName')` and `socket.on('nameChange', myHandler)`

What exactly are you trying to achieve? Do the cases above not cover it?

**Comment by namel** [comment]
Having a string netscheme type only has the special advantage that it's easier than all the alternatives.  For example an object may have the player name which never changes.  But option 1 doesn't apply because each instance has a different name, and option 2 doesn't apply because the name is not an index.

So option 3 applies, but it's cumbersome.  Adding the name to the netscheme is a one-liner which "just works".

So maybe there could be a string type after all, but the serializer will need to be smart enough to avoid sending strings which haven't changed.

**Comment by z3t0** [comment]
I am trying to setup a way to have a player name attached to an object.

For some reason I have an issue where the first time a constructor is called for a Dynamic object the name is not autogenerated, but other times it is fine. It may just be a silly bug I am not seeing so I will spend some more time debugging and see how far I get.

I am not too fixated on a string in the net scheme but I think it would be a nice convenient feature.

**Comment by namel** [comment]
hi @z3t0 I pushed a fix to r1.0.8 please try it out and let me know if it works.  The string will not actually be sent to the clients unless it has changed.
