### ISSUE TITLE
Make some sweet sweet documentation love to the Serializer types.

### ISSUE THREAD

**Issue by rateforx** [lance-gg/lance#84]
Also, "You should definitely add a more informative error for netScheme property definition".

**Comment by namel** [comment]
I've updated the docs in the develop branch, will take a while to propagate.  I also had to separate out the base types to a class `BaseTypes.js` in order to break a circular reference in `Serializer.js`  Using the base types directly from `Serializer.js` is now deprecated, and all the demo games should be updated at some point.
