### ISSUE TITLE
typescript type definition file?

### ISSUE THREAD

**Issue by ssatguru** [lance-gg/lance#90]
Considering using this with BabylonJS engine. 
BabylonJS and my application are written in TypeScript. 
Any chance of getting a typescript type definition file (.d.ts) for lance-gg ?

**Comment by namel** [comment]
I have no objection to a typescript definition file - if there is a pull request I'd be happy to integrate, I probably won't have time to implement this.

As for BabylonJS - also a great idea but not on the roadmap at the moment.   I'd be happy for a pull request.  Needs something like https://github.com/lance-gg/lance/blob/master/src/render/ThreeRenderer.js

**Comment by namel** [comment]
Great summary.

I have no objections to the proposed import syntax you suggest, in fact, it looks better than what we have now.  And proposal 1 is the most straightforward.  We'd need to maintain the typings file, but that seems like a reasonable impact which I can manage.  Would we need a sample game which takes advantage of this?

@OpherV please consider, I'd like to know your thoughts on this.

**Comment by andrewkolos** [comment]
Not sure an entire sample game would be completely necessary to test either change, though I am planning on making one regardless in the near future.

Exporting members in an `index.js` is generally straightforward, in my limited experience. When the change is ready, you could manually stick this fork in another project's `node_modules` folder and play around with importing things to see if it's to your liking, which I will probably do myself as a sanity check (not sure if there is a more elegant way).

As far as testing typings goes, not sure since I generally just rely on my IDE (VSCode or Webstorm) to tell me when there is a type error. I think this could be tested outside of an IDE with a `tsc --noEmit` (`tsc` is the TS compiler). Using Lance with TS could tested in manner similar to what I described above or with an entire sample game as a proof of concept.

I'll start putting something together in a fork when the weekend comes.

**Comment by namel** [comment]
Sounds good.  I'm using atom so hopefully I will benefit from this as well.  Let me know if you got something working, even on a fork, and I will try it out.

**Comment by OpherV** [comment]
@andrewkolos thanks for the detailed analysis!

In general I like the main export file, and having `import { ClientEngine } from ‘lance-gg’` rather than the custom webpack config we have now. It's something I've been wanting to do for a while now to make the API simpler with as little "black magic" as possible so this definitely seems like a good opportunity. After we have this in place I'll definitely want to slowly phase our existing codebase to use this ES6 style import paradigm as well.

My only concern with TS is the fact I'm personally not using it, and so I don't want to add the burden of maintaining TS to the already huge list of todo's we have in this project :) That's way I'm personally more inclined to make the changes required so that types can be defined and added externally, like you suggested. That way awesome Lance community members like yourself can take up on those tasks :)

**Comment by andrewkolos** [comment]
@OpherV Completely understandable! In this case, going with option 2 and contributing the typings to DefinitelyTyped and having them maintained separately and others makes the most sense.

And don't worry, the choice between options 1 and 2 does not effect how the export file needs to be laid out. The typings can be made to fit whatever export scheme the module ends up having, as far as I am aware.

**Comment by Christian7573** [comment]
Do we have one of these yet? Couldn't find anything inside this repo or in DefinitelyTyped. I'm making a project with Lance in TypeScript, so I'll contribute one if not.

**Comment by namel** [comment]
hi @Christian7573 that would be a great contribution.  Now that Lance is compiled with Rollup, the addition should be easy to do.  If you can contribute types, I can make sure it is maintained and kept up to date.

**Comment by Christian7573** [comment]
@namel Should I put the typings in this repo or in DefinietlyTyped?

**Comment by namel** [comment]
@Christian7573 I prefer putting it directly in the repo

**Comment by pacifist-airmash** [comment]
Hey guys, don't mind me! 

I have been involved in many projects under a different account.  PaperJS, P2, Matter, Phaser, Pixi.  When TypeScript came out, I was very active in bringing TypeScript support  (I wasn't a JS dude) and I frequently PR to Definitely Typed too. 

If there grows to be true interest in TypeScript support,  I would highly recommend something like concentrating on a JSDoc format that can be parsed to types automatically.  This is what Pixi v5 does.  The benefit is that anyone can update Docs, and if your Docs are outdated, the TypeScript guys complain (or fix the docs with PR).  And of course, you get good accurate typed documentation out of the bag for the non JS folks. 

Unfortunately I cannot give any insight on this mechanism as I have been away, but I would really consider that a solution (before wasting the dozens of hours for the next few years, of manually tracking commits like I did).

@namel  & @OpherV 

While here, this project is amazing.  I believe there is 1 book on this whole subject in the world, never mind a working library with such clean code.   I really applaud your efforts in pioneering this NEEDED js field.

**Comment by Christian7573** [comment]
@pacifist-airmash Sadly I've already ground out most of the definition files, however setting up a system like the one you mentioned does sound beneficial. I'll investigate how PIXI does it soon. Thank you for your advice and your contributions to those projects! (I've used all of them except paper 🙃)

**Comment by namel** [comment]
@pacifist-airmash  I like the idea of having the types in-lined in the code.  It increases the probability that the types will be correct, both in the docs and for TypeScript developers.  Having `*.d.ts` files automatically generated from doc annotations does make sense.  @Christian7573 any chance you will consider this approach?  I'm more than willing to help out.  From a brief look at pixi.js this looks very straightforward.

**Comment by Christian7573** [comment]
@namel Yup, just had a look at PIXI and it seems simple and effective. I've popped on to the lance slack also since this seems like a good time to correct/add documentation since I saw a good few places where there errors. I'll start work.

**Comment by namel** [comment]
handled in #132
